# Generated by Django 4.2.4 on 2023-09-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_userqueries', '0003_alter_userquery_group_alter_userquery_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqueryvalue',
            name='lookup',
            field=models.CharField(choices=[('__exact', 'Exact Match'), ('__contains', 'Contains'), ('__startswith', 'Starts With'), ('__endswith', 'Ends With'), ('__on', 'On'), ('__lt', 'Before'), ('__gt', 'After'), ('__lt', 'Less Than'), ('__gt', 'Greater Than'), ('__isnull', 'Blank')], help_text='Lookup', max_length=12, verbose_name='Lookup'),
        ),
    ]
