# Generated by Django 4.2.4 on 2023-09-05 17:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_userqueries", "0005_alter_filterreference_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FilterReference",
            new_name="UserFilterReference",
        ),
        migrations.AlterModelOptions(
            name="userfilterreference",
            options={
                "ordering": ["label"],
                "verbose_name": "User Filter Reference",
                "verbose_name_plural": "User Filter References",
            },
        ),
    ]
