# Generated by Django 5.0a1 on 2023-10-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_roles", "0001_initial"),
        (
            "django_userqueries",
            "0006_rename_filterreference_userfilterreference_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userquery",
            name="user",
            field=models.ForeignKey(
                help_text="The user that owns the object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)ss",
                to="django_roles.roleuser",
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="userqueryvalue",
            name="user",
            field=models.ForeignKey(
                help_text="The user that owns the object",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)ss",
                to="django_roles.roleuser",
                verbose_name="User",
            ),
        ),
    ]
